SET SQL_SAFE_UPDATES = 0;
SET FOREIGN_KEY_CHECKS = 0;

DELETE FROM usuarios WHERE id <> 3;

TRUNCATE TABLE ongs;
TRUNCATE TABLE enderecos;
TRUNCATE TABLE imagens;
TRUNCATE TABLE postagens;
TRUNCATE TABLE paginas;
TRUNCATE TABLE patrocinadores;
TRUNCATE TABLE voluntarios;
TRUNCATE TABLE doacoes;

SET FOREIGN_KEY_CHECKS = 1;
SET SQL_SAFE_UPDATES = 1;
