SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE enderecos;
TRUNCATE TABLE imagens;
TRUNCATE TABLE usuarios;
TRUNCATE TABLE ongs;
TRUNCATE TABLE postagens;
TRUNCATE TABLE paginas;
TRUNCATE TABLE patrocinadores;
TRUNCATE TABLE voluntarios;
TRUNCATE TABLE doacoes;

SET FOREIGN_KEY_CHECKS = 1;
